base_url = "https://www.wheelofheaven.io"
default_language = "en"
title = "Wheel of Heaven"
description = "The democratization of the Age of Aquarius starts here. Wheel of Heaven is a knowledge base exploring the working hypothesis that life on Earth was intelligently designed by an extraterrestrial civilization, the so-called Elohim."
compile_sass = true
build_search_index = true

[markdown]
highlight_code = false

[search]
index_format = "fuse_json"

[extra]
# Put all your custom variables here

# Languages configuration
#
# Supported languages (for now):
# en, de, fr, es, ru, ja, zh

[translations]
tagline = "Mapping our engineered origins with evidence."
strapline = "Wheel of Heaven is an open, multilingual atlas that links ancient claims of extraterrestrial design to today’s peer-reviewed science."
elevatorPitch = "Wheel of Heaven is a public knowledge hub that threads Raëlian scriptures, world myth, and modern genomics into a critical, citation-rich narrative about humanity’s potential engineered origin. Read concise primers, explore annotated source texts, and explore the lore all transparent, open-source, and free."
footerWheelOfHeaven = "Wheel of Heaven"
footerGetStarted = "Get Started"
footerAbout = "About"
footerAbout_url = "/intro/wheel-of-heaven/"
footerHelloWorld = "Hello world!"
footerHelloWorld_url = "/articles/hello-world/"
footerFAQ = "Frequently Asked Questions"
footerFAQ_url = "/intro/faq/"
footerJumpRightIn = "Jump right in"
footerTheSetting = "The Setting"
footerTheSetting_url = "/intro/the-setting/"
footerTheFoundation = "The Foundation"
footerTheFoundation_url = "/intro/the-foundation/"
footerTheHypothesis = "The Hypothesis"
footerTheHypothesis_url = "/intro/the-hypothesis/"
footerPreamble = "Preamble"
footerPreamble_url = "/intro/preamble/"
footerSections = "Sections"
footerHome = "Home"
footerHome_url = "/"
footerIntro = "Intro"
footerIntro_url = "/intro/"
footerWiki = "Wiki"
footerWiki_url = "/wiki/"
footerArticles = "Articles"
footerArticles_url = "/articles/"
footerResources = "Resources"
footerResources_url = "/resources/"
footerPlatform = "Platform"
footerTags = "Tags"
footerTags_url = "/tags/"
footerCategories = "Categories"
footerCategories_url = "/categories/"
footerContributors = "Contributors"
footerContributors_url = "/contributors/"
footerRssFeed = "RSS Feed"
footerRssFeed_url = "/articles/index.xml"
footerCommunity = "Community"
footerCommunity_url = "/intro/community/"
footerCodeOfConduct = "Code of Conduct"
footerGithubDiscussion = "GitHub Discussion"
footerOpenSource = "Open Source"
footerSocialMedia = "Social Media"
footerDevelopment = "Development"
footerContribute = "How to Contribute"
footerChangelog = "Changelog"
footerCommitActivity = "Commit Activity"
footerReadme = "Readme"
footerPrivacyTerms = "Privacy & Terms"
footerPrivacyPolicy = "Privacy Policy"
footerPrivacyPolicy_url = "/privacy-policy/"
footerCookiePolicy = "Cookie Policy"
footerCookiePolicy_url = "/privacy-policy/"
footerSecurityPolicy = "Security Policy"
footerContact = "Contact"
footerContact_url = "/contact/"
footerAttribution = "This work is in the public domain"
footerAttributionSubline = "Content available under a <a href=\"https://github.com/wheelofheaven/wheelofheaven.io/blob/main/LICENSE\" class=\"link\" target=\"_blank\">Creative Commons license</a>"


[languages.de]
generate_feeds = true
build_search_index = true

[languages.de.translations]
tagline = "Mapping our engineered origins with evidence."
strapline = "Wheel of Heaven is an open, multilingual atlas that links ancient claims of extraterrestrial design to today’s peer-reviewed science."
elevatorPitch = "Wheel of Heaven is a public knowledge hub that threads Raëlian scriptures, world myth, and modern genomics into a critical, citation-rich narrative about humanity’s potential engineered origin. Read concise primers, explore annotated source texts, and explore the lore all transparent, open-source, and free."
footerAbout = "Über uns"
footerAboutLink = "/de/intro/wheel-of-heaven/"
footerHelloWorld = "Hallo Welt!"
footerHelloWorldLink = "/de/artikel/hallo-welt/"
footerFAQ = "Häufig Gestellte Fragen"
footerFAQLink = "/de/intro/faq/"
footerWhitePaper = "Weissbuch"
footerSections = "Abschnitte"
footerHome = "Startseite"
footerHomeLink = "/de/"
footerIntro = "Einführung"
footerIntroLink = "/de/intro/"
footerWiki = "Wiki"
footerWikiLink = "/de/wiki/"
footerArticles = "Artikel"
footerArticlesLink = "/de/articles/"
footerResources = "Ressourcen"
footerResourcesLink = "/de/resources/"
footerJumpRightIn = "Direkter Einstieg"
footerTheSetting = "Das Szenario"
footerTheSettingLink = "/de/intro/das-szenario/"
footerTheFoundation = "Das Fundament"
footerTheFoundationLink = "/de/intro/das-fundament/"
footerTheHypothesis = "Die Hypothese"
footerTheHypothesisLink = "/de/intro/die-hypothese/"
footerPreamble = "Einleitung"
footerPreambleLink = "/de/intro/einleitung/"
footerCommunity = "Community"
footerCommunityLink = "/de/intro/community/"
footerCodeOfConduct = "Verhaltenskodex"
footerGithubDiscussion = "GitHub Diskussion"
footerOpenSource = "Open Source"
footerSocialMedia = "Soziale Medien"
footerPlatform = "Plattform"
footerTags = "Tags"
footerTagsLink = "/de/tags/"
footerCategories = "Kategorien"
footerCategoriesLink = "/de/categories/"
footerContributors = "Mitwirkende"
footerContributorsLink = "/de/contributors/"
footerContribute = "Wie man Beitragen kann"
footerChangelog = "Changelog"
footerCommitActivity = "Commit-Aktivität"
footerReadme = "Lese mich"
footerRssFeed = "RSS-Feed"
footerRssFeedLink = "/de/artikel/index.xml"
footerPrivacyTerms = "Datenschutz & Bedingungen"
footerPrivacyPolicy = "Datenschutzbestimmungen"
footerPrivacyPolicyLink = "/privacy-policy/"
footerCookiePolicy = "Cookie-Richtlinie"
footerCookiePolicyLink = "/privacy-policy/"
footerSecurityPolicy = "Sicherheitsrichtlinie"
footerContact = "Kontakt"
footerContactLink = "/contact/"
footerAttribution = "Dieses Werk ist gemeinfrei"
footerAttributionSubline = "Inhalte verfügbar unter einer <a href=\"https://github.com/wheelofheaven/wheelofheaven.io/blob/main/LICENSE\" class=\"link\" target=\"_blank\">Creative Commons Lizenz</a>"

[languages.fr]
generate_feeds = true
build_search_index = true

[languages.fr.translations]
tagline = "Mapping our engineered origins with evidence."
strapline = "Wheel of Heaven is an open, multilingual atlas that links ancient claims of extraterrestrial design to today’s peer-reviewed science."
elevatorPitch = "Wheel of Heaven is a public knowledge hub that threads Raëlian scriptures, world myth, and modern genomics into a critical, citation-rich narrative about humanity’s potential engineered origin. Read concise primers, explore annotated source texts, and explore the lore all transparent, open-source, and free."
footerAbout = "À propos"
footerAboutLink = "/fr/intro/wheel-of-heaven/"
footerHelloWorld = "Bonjour le monde !"
footerHelloWorldLink = "/fr/articles/bonjour-le-monde/"
footerFAQ = "Questions Fréquemment Posées"
footerFAQLink = "/fr/intro/faq/"
footerWhitePaper = "Papier Blanc"
footerSections = "Sections"
footerHome = "Accueil"
footerHomeLink = "/fr/"
footerIntro = "Introduction"
footerIntroLink = "/fr/intro/"
footerWiki = "Wiki"
footerWikiLink = "/fr/wiki/"
footerArticles = "Articles"
footerArticlesLink = "/fr/articles/"
footerResources = "Ressources"
footerResourcesLink = "/fr/resources/"
footerJumpRightIn = "Plongez directement"
footerTheSetting = "Le Cadre"
footerTheSettingLink = "/fr/intro/le-cadre/"
footerTheFoundation = "Les Fondations"
footerTheFoundationLink = "/fr/intro/les-fondations/"
footerTheHypothesis = "L'Hypothèse"
footerTheHypothesisLink = "/fr/intro/lhypothèse/"
footerPreamble = "Préambule"
footerPreambleLink = "/fr/intro/préambule/"
footerCommunity = "Communauté"
footerCommunityLink = "/fr/intro/communaute/"
footerCodeOfConduct = "Code de Conduite"
footerGithubDiscussion = "Discussion GitHub"
footerOpenCollective = "Open Collective"
footerOpenSource = "Source Ouverte"
footerSocialMedia = "Médias Sociaux"
footerPlatform = "Plateforme"
footerTags = "Tags"
footerTagsLink = "/fr/tags/"
footerCategories = "Catégories"
footerCategoriesLink = "/fr/categories/"
footerContributors = "Contributeurs"
footerContributorsLink = "/fr/contributors/"
footerContribute = "Comment contribuer"
footerChangelog = "Journal des modifications"
footerCommitActivity = "Activité des Engagements"
footerReadme = "Lisez-moi"
footerRssFeed = "Flux RSS"
footerRssFeedLink = "/fr/articles/index.xml"
footerPrivacyTerms = "Confidentialité & Conditions"
footerPrivacyPolicy = "Politique de Confidentialité"
footerPrivacyPolicyLink = "/privacy-policy/"
footerCookiePolicy = "Politique sur les Cookies"
footerCookiePolicyLink = "/privacy-policy/"
footerSecurityPolicy = "Politique de Sécurité"
footerContact = "Contact"
footerContactLink = "/contact/"
footerAttribution = "Cette œuvre est dans le domaine public"
footerAttributionSubline = "Contenu disponible sous licence <a href=\"https://github.com/wheelofheaven/wheelofheaven.io/blob/main/LICENSE\" class=\"link\" target=\"_blank\">Creative Commons</a>"

[languages.es]
generate_feeds = true
build_search_index = true

[languages.es.translations]
tagline = "Mapping our engineered origins with evidence."
strapline = "Wheel of Heaven is an open, multilingual atlas that links ancient claims of extraterrestrial design to today’s peer-reviewed science."
elevatorPitch = "Wheel of Heaven is a public knowledge hub that threads Raëlian scriptures, world myth, and modern genomics into a critical, citation-rich narrative about humanity’s potential engineered origin. Read concise primers, explore annotated source texts, and explore the lore all transparent, open-source, and free."
footerAbout = "Acerca de"
footerAboutLink = "/es/intro/wheel-of-heaven/"
footerHelloWorld = "¡Hola mundo!"
footerHelloWorldLink = "/es/articulos/hola-mundo/"
footerFAQ = "Preguntas Frecuentes"
footerFAQLink = "/es/intro/faq/"
footerWhitePaper = "Libro Blanco"
footerSections = "Secciones"
footerHome = "Inicio"
footerHomeLink = "/es/"
footerIntro = "Introducción"
footerIntroLink = "/es/intro/"
footerWiki = "Wiki"
footerWikiLink = "/es/wiki/"
footerArticles = "Artículos"
footerArticlesLink = "/es/articles/"
footerResources = "Recursos"
footerResourcesLink = "/es/resources/"
footerJumpRightIn = "Adentrarse Directamente"
footerTheSetting = "El Marco"
footerTheSettingLink = "/es/intro/el-marco/"
footerTheFoundation = "Los Fundamentos"
footerTheFoundationLink = "/es/intro/los-fundamentos/"
footerTheHypothesis = "La Hipótesis"
footerTheHypothesisLink = "/es/intro/la-hipótesis/"
footerPreamble = "Preámbulo"
footerPreambleLink = "/es/intro/preámbulo/"
footerCommunity = "Comunidad"
footerCommunityLink = "/es/intro/comunidad/"
footerCodeOfConduct = "Código de Conducta"
footerGithubDiscussion = "Discusión en GitHub"
footerOpenSource = "Código Abierto"
footerSocialMedia = "Redes Sociales"
footerPlatform = "Plataforma"
footerTags = "Etiquetas"
footerTagsLink = "/es/etiquetas/"
footerCategories = "Categorías"
footerCategoriesLink = "/es/categories/"
footerContributors = "Colaboradores"
footerContributorsLink = "/es/contributors/"
footerContribute = "Cómo Contribuir"
footerChangelog = "Registro de Cambios"
footerCommitActivity = "Actividad de Commits"
footerReadme = "Léame"
footerRssFeed = "Fuente RSS"
footerRssFeedLink = "/es/articles/index.xml"
footerPrivacyTerms = "Privacidad y Términos"
footerPrivacyPolicy = "Política de Privacidad"
footerPrivacyPolicyLink = "/privacy-policy/"
footerCookiePolicy = "Política de Cookies"
footerCookiePolicyLink = "/privacy-policy/"
footerSecurityPolicy = "Política de Seguridad"
footerContact = "Contacto"
footerContactLink = "/contact/"
footerAttribution = "Esta obra es de dominio público"
footerAttributionSubline = "Contenido disponible bajo licencia <a href=\"https://github.com/wheelofheaven/wheelofheaven.io/blob/main/LICENSE\" class=\"link\" target=\"_blank\">Creative Commons</a>"

[languages.ru]
generate_feeds = true
build_search_index = true

[languages.ru.translations]
tagline = "Mapping our engineered origins with evidence."
strapline = "Wheel of Heaven is an open, multilingual atlas that links ancient claims of extraterrestrial design to today’s peer-reviewed science."
elevatorPitch = "Wheel of Heaven is a public knowledge hub that threads Raëlian scriptures, world myth, and modern genomics into a critical, citation-rich narrative about humanity’s potential engineered origin. Read concise primers, explore annotated source texts, and explore the lore all transparent, open-source, and free."
footerAbout = "О проекте"
footerAboutLink = "/ru/intro/wheel-of-heaven/"
footerHelloWorld = "Привет, мир!"
footerHelloWorldLink = "/ru/articles/привет-мир/"
footerFAQ = "Часто Задаваемые Вопросы"
footerFAQLink = "/ru/intro/faq/"
footerWhitePaper = "Белая книга"
footerSections = "Разделы"
footerHome = "Главная"
footerHomeLink = "/ru/"
footerIntro = "Введение"
footerIntroLink = "/ru/intro/"
footerWiki = "Вики"
footerWikiLink = "/ru/wiki/"
footerArticles = "Статьи"
footerArticlesLink = "/ru/articles/"
footerResources = "Ресурсы"
footerResourcesLink = "/ru/resources/"
footerJumpRightIn = "Начать с Главного"
footerTheSetting = "Обстановка"
footerTheSettingLink = "/ru/intro/обстановка/"
footerTheFoundation = "Основание"
footerTheFoundationLink = "/ru/intro/основание/"
footerTheHypothesis = "Гипотеза"
footerTheHypothesisLink = "/ru/intro/гипотеза/"
footerPreamble = "Предисловие"
footerPreambleLink = "/ru/intro/предисловие/"
footerCommunity = "Сообщество"
footerCommunityLink = "/ru/intro/сообщество/"
footerCodeOfConduct = "Кодекс Поведения"
footerGithubDiscussion = "Обсуждение на GitHub"
footerOpenCollective = "Открытое Коллектив"
footerOpenSource = "Открытый Исходный Код"
footerSocialMedia = "Социальные Сети"
footerPlatform = "Платформа"
footerTags = "Теги"
footerTagsLink = "/ru/tags/"
footerCategories = "Категории"
footerCategoriesLink = "/ru/categories/"
footerContributors = "Участники"
footerContributorsLink = "/ru/contributors/"
footerContribute = "Как Внести Вклад"
footerChangelog = "Журнал Изменений"
footerCommitActivity = "Активность Коммитов"
footerReadme = "Прочтите Меня"
footerRssFeed = "RSS-лента"
footerRssFeedLink = "/ru/articles/index.xml"
footerPrivacyTerms = "Конфиденциальность и Условия"
footerPrivacyPolicy = "Политика Конфиденциальности"
footerPrivacyPolicyLink = "/privacy-policy/"
footerCookiePolicy = "Политика использования Cookie"
footerCookiePolicyLink = "/privacy-policy/"
footerSecurityPolicy = "Политика Безопасности"
footerContact = "Контакт"
footerContactLink = "/contact/"
footerAttribution = "Это произведение находится в общественном достоянии"
footerAttributionSubline = "Контент доступен под лицензией <a href=\"https://github.com/wheelofheaven/wheelofheaven.io/blob/main/LICENSE\" class=\"link\" target=\"_blank\">Creative Commons</a>"

[languages.ja]
# generate_feeds = true
# build_search_index = true

[languages.ja.translations]
tagline = "Mapping our engineered origins with evidence."
strapline = "Wheel of Heaven is an open, multilingual atlas that links ancient claims of extraterrestrial design to today’s peer-reviewed science."
elevatorPitch = "Wheel of Heaven is a public knowledge hub that threads Raëlian scriptures, world myth, and modern genomics into a critical, citation-rich narrative about humanity’s potential engineered origin. Read concise primers, explore annotated source texts, and explore the lore all transparent, open-source, and free."
footerAbout = "紹介"
footerAboutLink = "/ja/intro/wheel-of-heaven/"
footerHelloWorld = "こんにちは、世界！"
footerHelloWorldLink = "/ja/articles/こんにちは世界/"
footerFAQ = "よくある質問"
footerFAQLink = "/ja/intro/faq/"
footerWhitePaper = "ホワイトペーパー"
footerSections = "セクション"
footerHome = "ホーム"
footerHomeLink = "/ja/"
footerIntro = "イントロ"
footerIntroLink = "/ja/intro/"
footerWiki = "ウィキ"
footerWikiLink = "/ja/wiki/"
footerArticles = "記事"
footerArticlesLink = "/ja/articles/"
footerResources = "リソース"
footerResourcesLink = "/ja/resources/"
footerJumpRightIn = "すぐに始める"
footerTheSetting = "舞台設定"
footerTheSettingLink = "/ja/intro/舞台設定/"
footerTheFoundation = "基礎"
footerTheFoundationLink = "/ja/intro/基礎/"
footerTheHypothesis = "仮説"
footerTheHypothesisLink = "/ja/intro/仮説/"
footerPreamble = "序文"
footerPreambleLink = "/ja/intro/序文/"
footerCommunity = "コミュニティ"
footerCommunityLink = "/ja/intro/コミュニティ/"
footerCodeOfConduct = "行動規範"
footerGithubDiscussion = "GitHubでのディスカッション"
footerOpenSource = "オープンソース"
footerSocialMedia = "ソーシャルメディア"
footerPlatform = "プラットフォーム"
footerTags = "タグ"
footerTagsLink = "/ja/tags/"
footerCategories = "カテゴリー"
footerCategoriesLink = "/ja/categories/"
footerContributors = "貢献者"
footerContributorsLink = "/ja/contributors/"
footerContribute = "貢献する方法"
footerChangelog = "変更ログ"
footerCommitActivity = "コミットアクティビティ"
footerReadme = "README"
footerRssFeed = "RSSフィード"
footerRssFeedLink = "/ja/articles/index.xml"
footerPrivacyTerms = "プライバシーと利用規約"
footerPrivacyPolicy = "プライバシーポリシー"
footerPrivacyPolicyLink = "/privacy-policy/"
footerCookiePolicy = "クッキーポリシー"
footerCookiePolicyLink = "/privacy-policy/"
footerSecurityPolicy = "セキュリティポリシー"
footerContact = "連絡先"
footerContactLink = "/contact/"
footerAttribution = "この作品はパブリックドメインです"
footerAttributionSubline = "コンテンツは<a href=\"https://github.com/wheelofheaven/wheelofheaven.io/blob/main/LICENSE\" class=\"link\" target=\"_blank\">Creative Commonsライセンス</a>の下で利用可能です"

[languages.zh]
generate_feeds = true
# build_search_index = true

[languages.zh.translations]
tagline = "Mapping our engineered origins with evidence."
strapline = "Wheel of Heaven is an open, multilingual atlas that links ancient claims of extraterrestrial design to today’s peer-reviewed science."
elevatorPitch = "Wheel of Heaven is a public knowledge hub that threads Raëlian scriptures, world myth, and modern genomics into a critical, citation-rich narrative about humanity’s potential engineered origin. Read concise primers, explore annotated source texts, and explore the lore all transparent, open-source, and free."
footerAbout = "关于"
footerAboutLink = "/zh/intro/wheel-of-heaven/"
footerHelloWorld = "你好，世界！"
footerHelloWorldLink = "/zh/articles/你好世界/"
footerFAQ = "常见问题"
footerFAQLink = "/zh/intro/faq/"
footerWhitePaper = "白皮书"
footerSections = "版块"
footerHome = "首页"
footerHomeLink = "/zh/"
footerIntro = "简介"
footerIntroLink = "/zh/intro/"
footerWiki = "维基"
footerWikiLink = "/zh/wiki/"
footerArticles = "文章"
footerArticlesLink = "/zh/articles/"
footerResources = "资源"
footerResourcesLink = "/zh/resources/"
footerJumpRightIn = "直接深入"
footerTheSetting = "背景设置"
footerTheSettingLink = "/zh/intro/背景设置/"
footerTheFoundation = "基础"
footerTheFoundationLink = "/zh/intro/基础/"
footerTheHypothesis = "假设"
footerTheHypothesisLink = "/zh/intro/假设/"
footerPreamble = "序言"
footerPreambleLink = "/zh/intro/序言/"
footerCommunity = "社区"
footerCommunityLink = "/zh/intro/社区/"
footerCodeOfConduct = "行为守则"
footerGithubDiscussion = "GitHub 讨论"
footerOpenCollective = "开放集体"
footerOpenSource = "开源"
footerSocialMedia = "社交媒体"
footerPlatform = "平台"
footerTags = "标签"
footerTagsLink = "/zh/tags/"
footerCategories = "分类"
footerCategoriesLink = "/zh/categories/"
footerContributors = "贡献者"
footerContributorsLink = "/zh/contributors/"
footerContribute = "如何贡献"
footerChangelog = "变更日志"
footerCommitActivity = "提交活动"
footerReadme = "自述文件"
footerRssFeed = "RSS 订阅"
footerRssFeedLink = "/zh/articles/index.xml"
footerPrivacyTerms = "隐私与条款"
footerPrivacyPolicy = "隐私政策"
footerPrivacyPolicyLink = "/privacy-policy/"
footerCookiePolicy = "Cookie 政策"
footerCookiePolicyLink = "/privacy-policy/"
footerSecurityPolicy = "安全政策"
footerContact = "联系方式"
footerContactLink = "/contact/"
footerAttribution = "本作品属于公共领域"
footerAttributionSubline = "内容在<a href=\"https://github.com/wheelofheaven/wheelofheaven.io/blob/main/LICENSE\" class=\"link\" target=\"_blank\">知识共享许可证</a>下提供"
